/**
 * Patch flags are optimization hints generated by the compiler.
 * when a block with dynamicChildren is encountered during diff, the algorithm
 * enters "optimized mode". In this mode, we know that the vdom is produced by
 * a render function generated by the compiler, so the algorithm only needs to
 * handle updates explicitly marked by these patch flags.
 *
 * Patch flags can be combined using the | bitwise operator and can be checked
 * using the & operator, e.g.
 *
 * ```js
 * const flag = TEXT | CLASS
 * if (flag & TEXT) { ... }
 * ```
 *
 * Check the `patchElement` function in '../../runtime-core/src/renderer.ts' to see how the
 * flags are handled during diff.
 */
// 根据不同的 patchFlags 使用不同的 patch 方法
/**
 * patchFlag 分为两大类：
 *  1. patchFlag 大于 0 时，代表所对应的元素在 patchVNode 时或 render 时是可以被优化生成或者更新的
 *  2. patchFlag 小于 0 时，代表所对应的元素在 patchVNode 时是需要被 full diff 的，即进行递归遍历 VNode tree 的比较过程
 */
export const enum PatchFlags {
  /**
   * Indicates an element with dynamic textContent (children fast path)
   * 标识具有动态 textContent（子级快速路径）的元素
   */
  TEXT = 1, // 1

  /**
   * Indicates an element with dynamic class binding.
   * 标识具有动态类绑定的元素
   */
  CLASS = 1 << 1, // 2

  /**
   * Indicates an element with dynamic style
   * The compiler pre-compiles static string styles into static objects
   * + detects and hoists inline static objects
   * e.g. style="color: red" and :style="{ color: 'red' }" both get hoisted as
   *   const style = { color: 'red' }
   *   render() { return e('div', { style }) }
   * 标识具有动态 style 的节点
   */
  STYLE = 1 << 2, // 4

  /**
   * Indicates an element that has non-class/style dynamic props.
   * Can also be on a component that has any dynamic props (includes
   * class/style). 
   * when this flag is present, the vnode also has a dynamicProps
   * array that contains the keys of the props that may change so the runtime
   * can diff them faster (without having to worry about removed props)
   * 标识具有非 class/style 的动态属性的节点.
   * 也可在组件上有动态属性包括 style/style.
   * 当这个标志存在时，vnode 还有一个 dynamicProps 数组，其中包含可能改变的道具的键，以便运行时可以更快地区分它们（而不必担心删除的道具）
   */
  PROPS = 1 << 3, // 8

  /**
   * Indicates an element with props with dynamic keys. When keys change, a full
   * diff is always needed to remove the old key. This flag is mutually
   * exclusive with CLASS, STYLE and PROPS.
   * 标识具有 props 和 动态 key 的节点。
   * 当 key 改变，一个完整的 diff 总是需要完全的删除旧的 key。
   * 这个 flag 和 CLASS、STYLE、PROPS 是互斥的
   */
  FULL_PROPS = 1 << 4, // 16

  /**
     * Indicates an element with event listeners (which need to be attached
     * during hydration)
   * 标识具有事件监听的节点
   */
  HYDRATE_EVENTS = 1 << 5, // 32

  /**
   * Indicates a fragment whose children order doesn't change.
   * 标识一个不会改变子节点顺序的 fragment 
   */
  STABLE_FRAGMENT = 1 << 6, // 64

  /**
   * Indicates a fragment with keyed or partially keyed children
   * 标识有 key 的 fragment 或者部分有 key 的子节点
   */
  KEYED_FRAGMENT = 1 << 7, // 128

  /**
   * Indicates a fragment with unkeyed children.
   * 标识一个子节点没有 key 的 framgent
   */
  UNKEYED_FRAGMENT = 1 << 8, // 256

  /**
   * Indicates an element that only needs non-props patching, e.g. ref or
   * directives (onVnodeXXX hooks). since every patched vnode checks for refs
   * and onVnodeXXX hooks, it simply marks the vnode so that a parent block
   * will track it.
   * 标识只需要非 props 比较的节点
   */
  NEED_PATCH = 1 << 9, // 512

  /**
   * Indicates a component with dynamic slots (e.g. slot that references a v-for
   * iterated value, or dynamic slot names).
   * Components with this flag are always force updated.
   * 标识一个动态 slots 的组件
   */
  DYNAMIC_SLOTS = 1 << 10, // 1024

  /**
   * Indicates a fragment that was created only because the user has placed
   * comments at the root level of a template. This is a dev-only flag since
   * comments are stripped in production.
   */
  DEV_ROOT_FRAGMENT = 1 << 11,

  /**
   * SPECIAL FLAGS -------------------------------------------------------------
   * Special flags are negative integers. They are never matched against using
   * bitwise operators (bitwise matching should only happen in branches where
   * patchFlag > 0), and are mutually exclusive. When checking for a special
   * flag, simply check patchFlag === FLAG.
   */

  /**
   * Indicates a hoisted static vnode. This is a hint for hydration to skip
   * the entire sub tree since static content never needs to be updated.
   * 标识一个静态节点，静态节点从来不会更新，在优化的时候可以跳过
   */
  HOISTED = -1,
  /**
   * A special flag that indicates that the diffing algorithm should bail out
   * of optimized mode. For example, on block fragments created by renderSlot()
   * when encountering non-compiler generated slots (i.e. manually written
   * render functions, which should always be fully diffed)
   * OR manually cloneVNodes
   * 指示在 diff 过程应该要退出优化模式，不是 render 函数生成的一些元素，例如 renderSlot
   */
  BAIL = -2
}

/**
 * dev only flag -> name mapping
 */
export const PatchFlagNames = {
  [PatchFlags.TEXT]: `TEXT`,
  [PatchFlags.CLASS]: `CLASS`,
  [PatchFlags.STYLE]: `STYLE`,
  [PatchFlags.PROPS]: `PROPS`,
  [PatchFlags.FULL_PROPS]: `FULL_PROPS`,
  [PatchFlags.HYDRATE_EVENTS]: `HYDRATE_EVENTS`,
  [PatchFlags.STABLE_FRAGMENT]: `STABLE_FRAGMENT`,
  [PatchFlags.KEYED_FRAGMENT]: `KEYED_FRAGMENT`,
  [PatchFlags.UNKEYED_FRAGMENT]: `UNKEYED_FRAGMENT`,
  [PatchFlags.NEED_PATCH]: `NEED_PATCH`,
  [PatchFlags.DYNAMIC_SLOTS]: `DYNAMIC_SLOTS`,
  [PatchFlags.DEV_ROOT_FRAGMENT]: `DEV_ROOT_FRAGMENT`,
  [PatchFlags.HOISTED]: `HOISTED`,
  [PatchFlags.BAIL]: `BAIL`
}
